name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ '5.0.100' ] #[ '3.0', '3.1.x', '5.0.100' ]
        os: [ 'ubuntu-latest' ] #[ 'Windows-latest', 'ubuntu-latest', 'macOS-latest' ]
    defaults:
      run:
        shell: pwsh
    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.os }} with .NET ${{ matrix.dotnet-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Resetting nuget
      run: dotnet clean -c Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create NuGet package
      run: dotnet pack src/BluePrism.Hackathon.Package.Temp/BluePrism.Hackathon.Package.Temp.csproj --output nuget-packages --configuration Release -p:PackageVersion=0.1.0-preview-0001
    - name: Publish NuGet package
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
